### ISSUE TITLE
Error at `component push -c fruit-client-sb`

### ISSUE THREAD

**Issue by iocanel** [halkyonio/operator#156]
Local changes detected for 'fruit-client-sb' component: about to push source code to remote cluster
```
✗  Uploading /home/iocanel/rhte/fruit-client-sb.tar
FATA[0001] error running push: error uploading file: exit status 1
```

**Comment by metacosm** [comment]
After investigating, this issue occurs because the status of the component is not properly updated when a link is created. The component records its associated pod name for future use in its status' `PodName` field. However, when a link is created, the pod name changes (because the associated `Deployment` is changed due to environment variables or secret injection). The issue is caused because halkyon is not made aware of this pod change, thus failing to properly update the component's status. This results in the component trying to use an invalid pod name when pushing the code.
